export const appElement = {
    theme: document.querySelector('.theme__image'),
    body: document.querySelector('body'),
    topForm: document.querySelector('.top__form'),
    gridContainer: document.getElementById('grid'),
    form: document.querySelectorAll('form'),
    largeImage: document.getElementById('image__large'),
    largeImageContainer: document.querySelector('#large__image div'),
    imageContainer: document.querySelector('.image__container'),
    imageGrid: document.querySelector('.curated__grid'),
    curatedLoader: document.querySelector('.loader'),
    LoaderChild: document.querySelectorAll('.lds-facebook div'),
    topLoader: document.querySelector('.image__container .loader__container'),
    grid: document.getElementById('grid'),
    imageDiv: document.querySelectorAll('#grid div'),
    nextBtn: document.querySelector('.load__more'),
    pagination: document.querySelector('.search__loadMore'),
    loadMore: document.querySelector('.container'),
    searchedGrid: document.querySelector('.search__grid'),
    searchedContainer: document.querySelector('.search__container'),
    searchedLoader: document.querySelector('.search__container .loader__container'),
    section: document.querySelectorAll('.section'),
    header: document.querySelector('header')
};
// appElement.searchedLoader.style.display = 'none';
